import { Language } from '../../lang/Languages'

const {
    toshkents,
    bektemir,
    mirobod,
    mirzoulogbek,
    sergeli,
    olmazor,
    uchtepa,
    shayxontohur,
    yashnobod,
    chilonzor,
    yunusobod,
    yakkasaroy,
    // toshkent viloyati
    toshkentv,
    angren,
    bekobods,
    bekobodt,
    boka,
    bostonliq,
    chinoz,
    chirchiq,
    ortachirchiq,
    ohangaron,
    olmaliq,
    oqqorgon,
    parkent,
    piskent,
    qibray,
    quyichirchiq,
    yangiyol,
    yuqorichirchiq,
    zangiota,
    // andijon viloyati
    andijon,
    andijons,
    andijont,
    asaka,
    baliqchi,
    boz,
    buloqboshi,
    izboskan,
    jalolquduq,
    marhamat,
    oltinkol,
    paxtaobod,
    qorgontepa,
    shahrixon,
    ulugnor,
    xojaobod,
    xonobod,
    // namangan viloyati
    namangan,
    chortoq,
    chust,
    kosonsoy,
    mingbuloq,
    namangans,
    namangant,
    norin,
    pop,
    toraqorgon,
    uchqorgon,
    uychi,
    yangiqorgon,
    // fargona viloyati
    fargona,
    beshariq,
    bogdod,
    buvayda,
    dangara,
    fargonas,
    fargonat,
    furqat,
    margilon,
    ozbekiston,
    oltiariq,
    qoqon,
    qoshtepa,
    quva,
    quvasoy,
    rishton,
    sox,
    toshloq,
    uchkoprik,
    yozyovon,
    // buxoro viloyati
    buxoro,
    buxoros,
    buxorot,
    gijduvon,
    jondor,
    kogons,
    kogont,
    olot,
    peshku,
    qorakol,
    qorovulbozor,
    romitan,
    shofirkon,
    vobkent,
    // xorazm viloyati
    xorazm,
    bogot,
    gurlan,
    qoshkopir,
    shovot,
    urganchs,
    urgancht,
    xazorasp,
    xiva,
    xonqa,
    yangiariq,
    yangibozor,
    // surxandaryo viloyati
    surxandaryo,
    angor,
    bandixon,
    boysun,
    denov,
    jarqorgon,
    muzrobot,
    oltinsoy,
    qiziriq,
    qumqorgon,
    sariosiyo,
    sherobod,
    shorchi,
    termizs,
    termizt,
    uzun,
    // qashqadaryo viloyati
    qashqadaryo,
    chiroqchi,
    dehqonobod,
    guzor,
    kasbi,
    kitob,
    koson,
    mirishkor,
    muborak,
    nishon,
    qamashi,
    qarshis,
    qarshit,
    shahrisabz,
    yakkabog,
    // jizzax viloyati
    jizzax,
    arnasoy,
    baxmal,
    dostlik,
    forish,
    gallaorol,
    jizzaxs,
    jizzaxt,
    mirzachol,
    paxtakor,
    yangiobod,
    zafarobod,
    zarband,
    zomin,
    // navoiy viloyati
    navoiy,
    karmana,
    konimex,
    navbahor,
    navoiys,
    nurota,
    qiziltepa,
    tomdi,
    uchquduq,
    xatirchi,
    zarafshon,
    // samarqand viloyati
    samarqand,
    bulungur,
    ishtixon,
    jomboy,
    kattaqorgons,
    kattaqorgont,
    narpay,
    nurobod,
    oqdaryo,
    pastdargom,
    paxtachi,
    poyariq,
    qoshrabot,
    samarqands,
    samarqandt,
    toyloq,
    urgut,
    // sirdaryo viloyati
    sirdaryo,
    boyovut,
    gulistons,
    gulistont,
    oqoltin,
    sardoba,
    sayxunobod,
    shirin,
    sirdaryot,
    xovos,
    yangiyer,
} = Language

const Areas = [
    // toshkent shahri
    {
        area: { label: toshkents, value: 'toshkents' },
        district: [
            { label: bektemir, value: 'bektemir' },
            { label: mirobod, value: 'mirobod' },
            { label: mirzoulogbek, value: 'mirzoulogbek' },
            { label: sergeli, value: 'sergeli' },
            { label: olmazor, value: 'olmazor' },
            { label: uchtepa, value: 'uchtepa' },
            { label: shayxontohur, value: 'shayxontohur' },
            { label: yashnobod, value: 'yashnobod' },
            { label: chilonzor, value: 'chilonzor' },
            { label: yunusobod, value: 'yunusobod' },
            { label: yakkasaroy, value: 'yakkasaroy' },
        ],
    },
    // toshkent viloyati
    {
        area: { label: toshkentv, value: 'toshkentv' },
        district: [
            { label: angren, value: 'angren' },
            { label: bekobods, value: 'bekobods' },
            { label: bekobodt, value: 'bekobodt' },
            { label: boka, value: 'boka' },
            { label: bostonliq, value: 'bostonliq' },
            { label: chinoz, value: 'chinoz' },
            { label: chirchiq, value: 'chirchiq' },
            { label: ortachirchiq, value: 'ortachirchiq' },
            { label: ohangaron, value: 'ohangaron' },
            { label: olmaliq, value: 'olmaliq' },
            { label: oqqorgon, value: 'oqqorgon' },
            { label: parkent, value: 'parkent' },
            { label: piskent, value: 'piskent' },
            { label: qibray, value: 'qibray' },
            { label: quyichirchiq, value: 'quyichirchiq' },
            { label: yangiyol, value: 'yangiyol' },
            { label: yuqorichirchiq, value: 'yuqorichirchiq' },
            { label: zangiota, value: 'zangiota' },
        ],
    },
    // andijon viloyati
    {
        area: { label: andijon, value: 'andijon' },
        district: [
            { label: andijons, value: 'andijons' },
            { label: andijont, value: 'andijont' },
            { label: asaka, value: 'asaka' },
            { label: baliqchi, value: 'baliqchi' },
            { label: boz, value: 'boz' },
            { label: buloqboshi, value: 'buloqboshi' },
            { label: izboskan, value: 'izboskan' },
            { label: jalolquduq, value: 'jalolquduq' },
            { label: marhamat, value: 'marhamat' },
            { label: oltinkol, value: 'oltinkol' },
            { label: paxtaobod, value: 'paxtaobod' },
            { label: qorgontepa, value: 'qorgontepa' },
            { label: shahrixon, value: 'shahrixon' },
            { label: ulugnor, value: 'ulugnor' },
            { label: xojaobod, value: 'xojaobod' },
            { label: xonobod, value: 'xonobod' },
        ],
    },
    // namangan viloyati
    {
        area: { label: namangan, value: 'namangan' },
        district: [
            { label: chortoq, value: 'chortoq' },
            { label: chust, value: 'chust' },
            { label: kosonsoy, value: 'kosonsoy' },
            { label: mingbuloq, value: 'mingbuloq' },
            { label: namangans, value: 'namangans' },
            { label: namangant, value: 'namangant' },
            { label: norin, value: 'norin' },
            { label: pop, value: 'pop' },
            { label: toraqorgon, value: 'toraqorgon' },
            { label: uchqorgon, value: 'uchqorgon' },
            { label: uychi, value: 'uychi' },
            { label: yangiqorgon, value: 'yangiqorgon' },
        ],
    },
    // fargona viloyati
    {
        area: { label: fargona, value: 'fargona' },
        district: [
            { label: beshariq, value: 'beshariq' },
            { label: bogdod, value: 'bogdod' },
            { label: buvayda, value: 'buvayda' },
            { label: dangara, value: 'dangara' },
            { label: fargonas, value: 'fargonas' },
            { label: fargonat, value: 'fargonat' },
            { label: furqat, value: 'furqat' },
            { label: margilon, value: 'margilon' },
            { label: ozbekiston, value: 'ozbekiston' },
            { label: oltiariq, value: 'oltiariq' },
            { label: qoqon, value: 'qoqon' },
            { label: qoshtepa, value: 'qoshtepa' },
            { label: quva, value: 'quva' },
            { label: quvasoy, value: 'quvasoy' },
            { label: rishton, value: 'rishton' },
            { label: sox, value: 'sox' },
            { label: toshloq, value: 'toshloq' },
            { label: uchkoprik, value: 'uchkoprik' },
            { label: yozyovon, value: 'yozyovon' },
        ],
    },
    // buxoro viloyati
    {
        area: { label: buxoro, value: 'buxoro' },
        district: [
            { label: buxoros, value: 'buxoros' },
            { label: buxorot, value: 'buxorot' },
            { label: gijduvon, value: 'gijduvon' },
            { label: jondor, value: 'jondor' },
            { label: kogons, value: 'kogons' },
            { label: kogont, value: 'kogont' },
            { label: olot, value: 'olot' },
            { label: peshku, value: 'peshku' },
            { label: qorakol, value: 'qorakol' },
            { label: qorovulbozor, value: 'qorovulbozor' },
            { label: romitan, value: 'romitan' },
            { label: shofirkon, value: 'shofirkon' },
            { label: vobkent, value: 'vobkent' },
        ],
    },
    // xorazm viloyati
    {
        area: { label: xorazm, value: 'xorazm' },
        district: [
            { label: bogot, value: 'bogot' },
            { label: gurlan, value: 'gurlan' },
            { label: qoshkopir, value: 'qoshkopir' },
            { label: shovot, value: 'shovot' },
            { label: urganchs, value: 'urganchs' },
            { label: urgancht, value: 'urgancht' },
            { label: xazorasp, value: 'xazorasp' },
            { label: xiva, value: 'xiva' },
            { label: xonqa, value: 'xonqa' },
            { label: yangiariq, value: 'yangiariq' },
            { label: yangibozor, value: 'yangibozor' },
        ],
    },
    // surxandaryo viloyati
    {
        area: { label: surxandaryo, value: 'surxandaryo' },
        district: [
            { label: angor, value: 'angor' },
            { label: bandixon, value: 'bandixon' },
            { label: boysun, value: 'boysun' },
            { label: denov, value: 'denov' },
            { label: jarqorgon, value: 'jarqorgon' },
            { label: muzrobot, value: 'muzrobot' },
            { label: oltinsoy, value: 'oltinsoy' },
            { label: qiziriq, value: 'qiziriq' },
            { label: qumqorgon, value: 'qumqorgon' },
            { label: sariosiyo, value: 'sariosiyo' },
            { label: sherobod, value: 'sherobod' },
            { label: shorchi, value: 'shorchi' },
            { label: termizs, value: 'termizs' },
            { label: termizt, value: 'termizt' },
            { label: uzun, value: 'uzun' },
        ],
    },
    // qashqadaryo viloyati
    {
        area: { label: qashqadaryo, value: 'qashqadaryo' },
        district: [
            { label: chiroqchi, value: 'chiroqchi' },
            { label: dehqonobod, value: 'dehqonobod' },
            { label: guzor, value: 'guzor' },
            { label: kasbi, value: 'kasbi' },
            { label: kitob, value: 'kitob' },
            { label: koson, value: 'koson' },
            { label: mirishkor, value: 'mirishkor' },
            { label: muborak, value: 'muborak' },
            { label: nishon, value: 'nishon' },
            { label: qamashi, value: 'qamashi' },
            { label: qarshis, value: 'qarshis' },
            { label: qarshit, value: 'qarshit' },
            { label: shahrisabz, value: 'shahrisabz' },
            { label: yakkabog, value: 'yakkabog' },
        ],
    },
    // jizzax viloyati
    {
        area: { label: jizzax, value: 'jizzax' },
        district: [
            { label: arnasoy, value: 'arnasoy' },
            { label: baxmal, value: 'baxmal' },
            { label: dostlik, value: 'dostlik' },
            { label: forish, value: 'forish' },
            { label: gallaorol, value: 'gallaorol' },
            { label: jizzaxs, value: 'jizzaxs' },
            { label: jizzaxt, value: 'jizzaxt' },
            { label: mirzachol, value: 'mirzachol' },
            { label: paxtakor, value: 'paxtakor' },
            { label: yangiobod, value: 'yangiobod' },
            { label: zafarobod, value: 'zafarobod' },
            { label: zarband, value: 'zarband' },
            { label: zomin, value: 'zomin' },
        ],
    },
    // navoiy viloyati
    {
        area: { label: navoiy, value: 'navoiy' },
        district: [
            { label: karmana, value: 'karmana' },
            { label: konimex, value: 'konimex' },
            { label: navbahor, value: 'navbahor' },
            { label: navoiys, value: 'navoiys' },
            { label: nurota, value: 'nurota' },
            { label: qiziltepa, value: 'qiziltepa' },
            { label: tomdi, value: 'tomdi' },
            { label: uchquduq, value: 'uchquduq' },
            { label: xatirchi, value: 'xatirchi' },
            { label: zarafshon, value: 'zarafshon' },
        ],
    },
    // samarqand viloyati
    {
        area: { label: samarqand, value: 'samarqand' },
        district: [
            { label: bulungur, value: 'bulungur' },
            { label: ishtixon, value: 'ishtixon' },
            { label: jomboy, value: 'jomboy' },
            { label: kattaqorgons, value: 'kattaqorgons' },
            { label: kattaqorgont, value: 'kattaqorgont' },
            { label: narpay, value: 'narpay' },
            { label: nurobod, value: 'nurobod' },
            { label: oqdaryo, value: 'oqdaryo' },
            { label: pastdargom, value: 'pastdargom' },
            { label: paxtachi, value: 'paxtachi' },
            { label: poyariq, value: 'poyariq' },
            { label: qoshrabot, value: 'qoshrabot' },
            { label: samarqands, value: 'samarqands' },
            { label: samarqandt, value: 'samarqandt' },
            { label: toyloq, value: 'toyloq' },
            { label: urgut, value: 'urgut' },
        ],
    },
    // samarqand viloyati
    {
        area: { label: sirdaryo, value: 'sirdaryo' },
        district: [
            { label: boyovut, value: 'boyovut' },
            { label: gulistons, value: 'gulistons' },
            { label: gulistont, value: 'gulistont' },
            { label: oqoltin, value: 'oqoltin' },
            { label: sardoba, value: 'sardoba' },
            { label: sayxunobod, value: 'sayxunobod' },
            { label: shirin, value: 'shirin' },
            { label: sirdaryot, value: 'sirdaryot' },
            { label: xovos, value: 'xovos' },
            { label: yangiyer, value: 'yangiyer' },
        ],
    },
]

export default Areas
